import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className={`${styles.connectButtonTopRight}`}>
        <ConnectButton />
      </div>
      <main className={styles.main}>
        {/* Other main content here */}
      </main>
      <footer className={styles.footer}>
        {/* Keep this footer empty or add your own content */}
      </footer>
    </div>
  );
};

export default Home;
